baseURL = 'https://jorgenhanisch.github.io/resyme/'
locale = 'nb-no'
title = 'Resyme'
theme = 'blank'
[params]
  sanityUrl = "https://gukxnj2e.api.sanity.io/v2021-10-21/data/query/production?query=*[_type == 'post']"

# Hovedmenyen
[[menu.main]]
    identifier = "arbeider"
    name = "Arbeider"
    url = "/arbeider/automedia/"  # Her peker vi hovedlenken direkte til undersiden
    weight = 2

[[menu.main]]
    identifier = "kompetanse"
    name = "Kompetanse"
    url = "/kompetanse/web/"      # Her peker vi hovedlenken direkte til undersiden
    weight = 3

# Undermeny-elementer (disse må ha parent)
[[menu.main]]
    parent = "arbeider"
    name = "Automedia"
    url = "/arbeider/automedia/"
    weight = 1

[[menu.main]]
    parent = "arbeider"
    name = "Lofotfisk"
    url = "/arbeider/lofotfisk/"
    weight = 2

[[menu.main]]
    parent = "arbeider"
    name = "HA Bygg"
    url = "/arbeider/habygg/"
    weight = 3

[[menu.main]]
    parent = "kompetanse"
    name = "Web"
    url = "/kompetanse/web/"
    weight = 1

[[menu.main]]
    parent = "kompetanse"
    name = "Markedsføring"
    url = "/kompetanse/markedsforing/"
    weight = 2

[[menu.main]]
    parent = "kompetanse"
    name = "Salg"
    url = "/kompetanse/salg/"
    weight = 3